### ISSUE TITLE
聽力不同題型的答對率被刷掉了

### ISSUE THREAD

**Issue by JustinChiangkc** [CryoliteZ/KMF-Unblock-Extension#1]
Hi,
It's a great tool.
Yet, the record of correct rate in listening section(question type segment) is not mine after I apply the extension.
It is still the wrong record after I remove the extension.
Is it possible to make it right?

Thanks

**Comment by JustinChiangkc** [comment]
Hi,
The record is corrected today.
It's still a great tool and save me lots of efforts.
Thank you for being so nice developing the extension.

Wish you all the best,
Justin

**Comment by alvinbhou** [comment]
Hi Justin,
  I have been investigating the issue since some other users had also encountered similar problems. I believe that the problem may due to KMF's new policy which could be fixed by using VPN. (The extension does not effect the records)

However, glad to hear that your issue has been fixed. Thanks for the kind words!

Alvin
